# Generated by Django 5.1.7 on 2025-03-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='رقم الهاتف')),
                ('skills', models.CharField(max_length=100, verbose_name='المهارات')),
                ('experience', models.CharField(max_length=120, verbose_name='الخبرة')),
            ],
            options={
                'verbose_name': 'متقدم',
                'verbose_name_plural': 'المتقدمين',
            },
        ),
    ]
